// GENERATED by scripts/build-britmet-films.cjs — do not edit by hand.
// Roofing films surveyed from britmet.co.uk (449 pages), de-branded, with the
// range names translated to plain English. Every film that plays is here; see
// the script for the ones that cannot be embedded. Re-run it to refresh.
import type { ProjectFilm } from "@/components/home/RealProjects";

export const BRITMET_FILMS: ProjectFilm[] = [
  {
    "label": "Ridges & hips",
    "title": "Tiling a ridge hip junction",
    "youtubeId": "FKKwIKY2Drg",
    "poster": "https://i.ytimg.com/vi/FKKwIKY2Drg/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Fitting a ridge end cap",
    "youtubeId": "kXI8gf8pY-c",
    "poster": "https://i.ytimg.com/vi/kXI8gf8pY-c/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Tiling a hip end cap",
    "youtubeId": "sitPdCyMXfk",
    "poster": "https://i.ytimg.com/vi/sitPdCyMXfk/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Tiling a hip",
    "youtubeId": "TvMAizoXD4A",
    "poster": "https://i.ytimg.com/vi/TvMAizoXD4A/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Tiling a verge/barge",
    "youtubeId": "FbL1NSGjgv0",
    "poster": "https://i.ytimg.com/vi/FbL1NSGjgv0/hqdefault.jpg"
  },
  {
    "label": "Flashings",
    "title": "Fitting a valley flashing",
    "youtubeId": "kU70Vqsy-6w",
    "poster": "https://i.ytimg.com/vi/kU70Vqsy-6w/hqdefault.jpg"
  },
  {
    "label": "Roof lights",
    "title": "Fitting a roof light",
    "youtubeId": "vxdR15ArMnI",
    "poster": "https://i.ytimg.com/vi/vxdR15ArMnI/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Fitting a ridge",
    "youtubeId": "ugKwM8T05kQ",
    "poster": "https://i.ytimg.com/vi/ugKwM8T05kQ/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Fitting an eave tray and eave vent strip",
    "youtubeId": "Vw5bTRSeqjE",
    "poster": "https://i.ytimg.com/vi/Vw5bTRSeqjE/hqdefault.jpg"
  },
  {
    "label": "Roof lights",
    "title": "Fitting a roof light window",
    "youtubeId": "nboAmoA_65E",
    "poster": "https://i.ytimg.com/vi/nboAmoA_65E/hqdefault.jpg"
  },
  {
    "label": "Roof tiling",
    "title": "Tiling a roof",
    "youtubeId": "XQDcySv7Za8",
    "poster": "https://i.ytimg.com/vi/XQDcySv7Za8/hqdefault.jpg"
  },
  {
    "label": "Insulation",
    "title": "Laying breather membrane",
    "youtubeId": "W9DltUHhqp8",
    "poster": "https://i.ytimg.com/vi/W9DltUHhqp8/hqdefault.jpg"
  },
  {
    "label": "Roof tiling",
    "title": "Setting out battens",
    "youtubeId": "9-OCrGrnwck",
    "poster": "https://i.ytimg.com/vi/9-OCrGrnwck/hqdefault.jpg"
  },
  {
    "label": "Roof tiling",
    "title": "Fitting the lightweight tile range",
    "youtubeId": "JaLsV-IwKvM",
    "poster": "https://i.ytimg.com/vi/JaLsV-IwKvM/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Cutting and bending a shingle hip end cap",
    "youtubeId": "1Awzw7lCl8c",
    "poster": "https://i.ytimg.com/vi/1Awzw7lCl8c/hqdefault.jpg"
  },
  {
    "label": "Flashings",
    "title": "Fitting hip flashing",
    "youtubeId": "NZx5tYXhxLo",
    "poster": "https://i.ytimg.com/vi/NZx5tYXhxLo/hqdefault.jpg"
  },
  {
    "label": "Flashings",
    "title": "Fitting ridge flashing",
    "youtubeId": "XIcgCNy9-yY",
    "poster": "https://i.ytimg.com/vi/XIcgCNy9-yY/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Fitting ridge vent",
    "youtubeId": "i8F8g3GPchU",
    "poster": "https://i.ytimg.com/vi/i8F8g3GPchU/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Fitting ridge to hip junction",
    "youtubeId": "hZn7OGk-Rkw",
    "poster": "https://i.ytimg.com/vi/hZn7OGk-Rkw/hqdefault.jpg"
  },
  {
    "label": "Roof tiling",
    "title": "Fitting shingle tiles",
    "youtubeId": "RwTmMgb8H0c",
    "poster": "https://i.ytimg.com/vi/RwTmMgb8H0c/hqdefault.jpg"
  },
  {
    "label": "Flashings",
    "title": "Fitting wall soaker",
    "youtubeId": "3O8D0-yYWCU",
    "poster": "https://i.ytimg.com/vi/3O8D0-yYWCU/hqdefault.jpg"
  },
  {
    "label": "Finishes",
    "title": "Using touch up kit",
    "youtubeId": "n34JCQS8-QM",
    "poster": "https://i.ytimg.com/vi/n34JCQS8-QM/hqdefault.jpg"
  },
  {
    "label": "Flashings",
    "title": "Cutting sheets for a valley flashing",
    "youtubeId": "9VQmpZSdzcE",
    "poster": "https://i.ytimg.com/vi/9VQmpZSdzcE/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Fitting eave tray & comb filler",
    "youtubeId": "npMzgfAlGvE",
    "poster": "https://i.ytimg.com/vi/npMzgfAlGvE/hqdefault.jpg"
  },
  {
    "label": "Flashings",
    "title": "Fitting battens for a valley",
    "youtubeId": "cC46BN8My7M",
    "poster": "https://i.ytimg.com/vi/cC46BN8My7M/hqdefault.jpg"
  },
  {
    "label": "Roof lights",
    "title": "Fitting a roof light window — pantile",
    "youtubeId": "ZKmgSx6bZf8",
    "poster": "https://i.ytimg.com/vi/ZKmgSx6bZf8/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Setting out battens ridge to eave system",
    "youtubeId": "ZtfuBZXJsIA",
    "poster": "https://i.ytimg.com/vi/ZtfuBZXJsIA/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Fitting ridge to eave sheets",
    "youtubeId": "GXFzfcnKMmQ",
    "poster": "https://i.ytimg.com/vi/GXFzfcnKMmQ/hqdefault.jpg"
  },
  {
    "label": "Insulation",
    "title": "Laying tacmat",
    "youtubeId": "o6P7WVXk6Vc",
    "poster": "https://i.ytimg.com/vi/o6P7WVXk6Vc/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Fitting ridge hip junction",
    "youtubeId": "PcZ24cJdy10",
    "poster": "https://i.ytimg.com/vi/PcZ24cJdy10/hqdefault.jpg"
  },
  {
    "label": "Ridges & hips",
    "title": "Fitting hip and hip end cap",
    "youtubeId": "6zo0PjvlaJA",
    "poster": "https://i.ytimg.com/vi/6zo0PjvlaJA/hqdefault.jpg"
  },
  {
    "label": "Case studies",
    "title": "Fitting a flat to pitch conversion",
    "youtubeId": "SOo1W_Nkkv8",
    "poster": "https://i.ytimg.com/vi/SOo1W_Nkkv8/hqdefault.jpg"
  },
  {
    "label": "Roofing",
    "title": "Fitting the structural roof lining",
    "youtubeId": "VGfP_7Iiec8",
    "poster": "https://i.ytimg.com/vi/VGfP_7Iiec8/maxresdefault.jpg"
  },
  {
    "label": "Case studies",
    "title": "Flat to pitch time-lapse",
    "youtubeId": "ZBNQl1FUc6w",
    "poster": "https://i.ytimg.com/vi/ZBNQl1FUc6w/hqdefault.jpg"
  },
  {
    "label": "Finishes",
    "title": "Stipple paint application: rolling the stipple paint from top to bottom",
    "youtubeId": "bAQddblj0KQ",
    "poster": "https://i.ytimg.com/vi/bAQddblj0KQ/hqdefault.jpg"
  },
  {
    "label": "Finishes",
    "title": "Stipple paint application: light textured finish",
    "youtubeId": "e-YXi9NzUxo",
    "poster": "https://i.ytimg.com/vi/e-YXi9NzUxo/hqdefault.jpg"
  },
  {
    "label": "Roofing systems",
    "title": "A look at the synthetic slate range",
    "youtubeId": "ie58cvek0kk",
    "poster": "https://i.ytimg.com/vi/ie58cvek0kk/maxresdefault.jpg"
  },
  {
    "label": "Roofing systems",
    "title": "A look at the lightweight slate range",
    "youtubeId": "dflWkMrDaDg",
    "poster": "https://i.ytimg.com/vi/dflWkMrDaDg/maxresdefault.jpg"
  },
  {
    "label": "Roofing systems",
    "title": "A look at the shingle tile range",
    "youtubeId": "EBq1ezOyQtQ",
    "poster": "https://i.ytimg.com/vi/EBq1ezOyQtQ/maxresdefault.jpg"
  },
  {
    "label": "Roofing systems",
    "title": "A look at the lightweight tile range",
    "youtubeId": "zQ8-_xJlTcs",
    "poster": "https://i.ytimg.com/vi/zQ8-_xJlTcs/maxresdefault.jpg"
  },
  {
    "label": "Sponsorship",
    "title": "Day one of the great holiday home show 2023",
    "youtubeId": "rdS-gJrqr1s",
    "poster": "https://i.ytimg.com/vi/rdS-gJrqr1s/hqdefault.jpg"
  },
  {
    "label": "Roofing systems",
    "title": "A look at the plain tile range",
    "youtubeId": "nqgecCHGaWs",
    "poster": "https://i.ytimg.com/vi/nqgecCHGaWs/maxresdefault.jpg"
  },
  {
    "label": "Roofing",
    "title": "Anti-vandal testing on lightweight slates",
    "youtubeId": "LrNyrUE2W7c",
    "poster": "https://i.ytimg.com/vi/LrNyrUE2W7c/hqdefault.jpg"
  },
  {
    "label": "Cladding",
    "title": "Fitting vertical junction flashing",
    "youtubeId": "rzPJAQUiJL8",
    "poster": "https://i.ytimg.com/vi/rzPJAQUiJL8/hqdefault.jpg"
  },
  {
    "label": "Insulation",
    "title": "Fitting PIR insulation boards with taped joints",
    "youtubeId": "LbpWs9IugsQ",
    "poster": "https://i.ytimg.com/vi/LbpWs9IugsQ/hqdefault.jpg"
  },
  {
    "label": "Insulation",
    "title": "Fitting breather membrane over counter battens",
    "youtubeId": "Qso1uRuzRbA",
    "poster": "https://i.ytimg.com/vi/Qso1uRuzRbA/hqdefault.jpg"
  },
  {
    "label": "Cladding",
    "title": "Fitting vertical window head jamb flashing",
    "youtubeId": "b3P40aQPahI",
    "poster": "https://i.ytimg.com/vi/b3P40aQPahI/hqdefault.jpg"
  },
  {
    "label": "Cladding",
    "title": "Fitting vertical end closer flashing",
    "youtubeId": "T7nu3n8fgC4",
    "poster": "https://i.ytimg.com/vi/T7nu3n8fgC4/hqdefault.jpg"
  },
  {
    "label": "Cladding",
    "title": "Fitting vertical battens",
    "youtubeId": "_dMNca2zE8o",
    "poster": "https://i.ytimg.com/vi/_dMNca2zE8o/hqdefault.jpg"
  },
  {
    "label": "Cladding",
    "title": "New counter battens to increase vertical void depth",
    "youtubeId": "Xx01PYYjw6o",
    "poster": "https://i.ytimg.com/vi/Xx01PYYjw6o/hqdefault.jpg"
  },
  {
    "label": "Cladding",
    "title": "Fitting vertical system",
    "youtubeId": "JoYww8AO_S0",
    "poster": "https://i.ytimg.com/vi/JoYww8AO_S0/hqdefault.jpg"
  },
  {
    "label": "Roofing systems",
    "title": "A look at the villa tile range",
    "youtubeId": "aWT0AgWRVVo",
    "poster": "https://i.ytimg.com/vi/aWT0AgWRVVo/maxresdefault.jpg"
  },
  {
    "label": "Cladding",
    "title": "Removing existing vertical cladding",
    "youtubeId": "hvEQEB2NLIw",
    "poster": "https://i.ytimg.com/vi/hvEQEB2NLIw/hqdefault.jpg"
  },
  {
    "label": "Roofing systems",
    "title": "A look at the profiled sheet range",
    "youtubeId": "9E45ALZ2frg",
    "poster": "https://i.ytimg.com/vi/9E45ALZ2frg/maxresdefault.jpg"
  },
  {
    "label": "Cladding",
    "title": "Removing existing vertical battens",
    "youtubeId": "IdVlCfzaLMM",
    "poster": "https://i.ytimg.com/vi/IdVlCfzaLMM/hqdefault.jpg"
  },
  {
    "label": "Roofing systems",
    "title": "A look at the pantile range",
    "youtubeId": "Gxtjq0s_OWM",
    "poster": "https://i.ytimg.com/vi/Gxtjq0s_OWM/maxresdefault.jpg"
  },
  {
    "label": "Roofing systems",
    "title": "A look at the roof panel range",
    "youtubeId": "nFYIevCeGRE",
    "poster": "https://i.ytimg.com/vi/nFYIevCeGRE/maxresdefault.jpg"
  },
  {
    "label": "Rainwater goods",
    "title": "Fitting rainwater goods",
    "youtubeId": "09TTy1Zz1XI",
    "poster": "https://i.ytimg.com/vi/09TTy1Zz1XI/maxresdefault.jpg"
  },
  {
    "label": "Cladding",
    "title": "Removal of existing vertical boards",
    "youtubeId": "7bb6pYZ3CaU",
    "poster": "https://i.ytimg.com/vi/7bb6pYZ3CaU/hqdefault.jpg"
  },
  {
    "label": "Industry",
    "title": "A news report on RAAC concrete in schools",
    "youtubeId": "t6MN6-VsGgM",
    "poster": "https://i.ytimg.com/vi/t6MN6-VsGgM/maxresdefault.jpg"
  },
  {
    "label": "Case studies",
    "title": "Residential roof renovation",
    "youtubeId": "r52LLG9Tr6E",
    "poster": "https://i.ytimg.com/vi/r52LLG9Tr6E/maxresdefault.jpg"
  },
  {
    "label": "Soffits & fascias",
    "title": "Fitting soffits and fascias",
    "youtubeId": "zEazbVkJ3yA",
    "poster": "https://i.ytimg.com/vi/zEazbVkJ3yA/maxresdefault.jpg"
  },
  {
    "label": "Industry",
    "title": "NBS in 60 seconds",
    "youtubeId": "zblLSJcFBd8",
    "poster": "https://i.ytimg.com/vi/zblLSJcFBd8/maxresdefault.jpg"
  },
  {
    "label": "Sponsorship",
    "title": "A sponsored driver's racing season",
    "youtubeId": "WKf-zHKVrgo",
    "poster": "https://i.ytimg.com/vi/WKf-zHKVrgo/maxresdefault.jpg"
  },
  {
    "label": "Case studies",
    "title": "Croydon site time-lapse",
    "youtubeId": "Cho0OEKtAF4",
    "poster": "https://i.ytimg.com/vi/Cho0OEKtAF4/hqdefault.jpg"
  },
  {
    "label": "Sponsorship",
    "title": "A sponsored race round at Hooton Park",
    "youtubeId": "rbDhI7FKEVQ",
    "poster": "https://i.ytimg.com/vi/rbDhI7FKEVQ/maxresdefault.jpg"
  },
  {
    "label": "Roofing",
    "title": "Anti-vandal testing on pantiles",
    "youtubeId": "LIRtk3vwgPA",
    "poster": "https://i.ytimg.com/vi/LIRtk3vwgPA/hqdefault.jpg"
  },
  {
    "label": "Roofing systems",
    "title": "Synthetic slate panels, close up",
    "src": "/home/real-projects/lightweight-slate-panels.mp4",
    "poster": "/home/real-projects/posters/lightweight-slate-panels.jpg",
    "portrait": true
  }
];
