// GENERATED by scripts/build-fakro-films.cjs — do not edit by hand.
// Skylight and roof-window films surveyed from fakro.com (691 pages), filtered
// to ids that still play, de-branded, and limited to the tiers named in that
// script. Re-run it to refresh.
import type { ProjectFilm } from "@/components/home/RealProjects";

export const FAKRO_FILMS: ProjectFilm[] = [
  {
    "label": "Real projects",
    "title": "A look inside the company",
    "youtubeId": "qvnLdbUdUzo",
    "poster": "https://i.ytimg.com/vi/qvnLdbUdUzo/maxresdefault.jpg"
  },
  {
    "label": "Real projects",
    "title": "Go Green - A new standard for a new era",
    "youtubeId": "XxEZcpZWltw",
    "poster": "https://i.ytimg.com/vi/XxEZcpZWltw/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Roof windows - Inspired by art, created in harmony with nature",
    "youtubeId": "1Mi0ZYKmdoQ",
    "poster": "https://i.ytimg.com/vi/1Mi0ZYKmdoQ/maxresdefault.jpg"
  },
  {
    "label": "Blinds",
    "title": "Windows and Blinds – Your Interior, Your Moments",
    "youtubeId": "r4eU9TgjH20",
    "poster": "https://i.ytimg.com/vi/r4eU9TgjH20/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Roof window production",
    "youtubeId": "pIilaC2w3wI",
    "poster": "https://i.ytimg.com/vi/pIilaC2w3wI/maxresdefault.jpg"
  },
  {
    "label": "Real projects",
    "title": "I always stand on the side of nature x Natalia Pacierpnik",
    "youtubeId": "W0_nQpegJqI",
    "poster": "https://i.ytimg.com/vi/W0_nQpegJqI/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Fitting an L-shaped window",
    "youtubeId": "EJse03r2F0g",
    "poster": "https://i.ytimg.com/vi/EJse03r2F0g/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "New generation of roof windows",
    "youtubeId": "15G_62ZbPcY",
    "poster": "https://i.ytimg.com/vi/15G_62ZbPcY/hqdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting a vertical slat",
    "youtubeId": "x0OEY6p4t3Q",
    "poster": "https://i.ytimg.com/vi/x0OEY6p4t3Q/maxresdefault.jpg"
  },
  {
    "label": "Flat roofs",
    "title": "Fitting a renovation flat roof window",
    "youtubeId": "ypV3jyE54t8",
    "poster": "https://i.ytimg.com/vi/ypV3jyE54t8/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting a fire resistant folding wooden loft ladder",
    "youtubeId": "DM-6WraGbDY",
    "poster": "https://i.ytimg.com/vi/DM-6WraGbDY/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting an energy-efficient loft ladder",
    "youtubeId": "ordoecUK2m0",
    "poster": "https://i.ytimg.com/vi/ordoecUK2m0/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting metal loft ladder stile ends",
    "youtubeId": "YtXT46HKl20",
    "poster": "https://i.ytimg.com/vi/YtXT46HKl20/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting wooden loft ladder stile ends",
    "youtubeId": "SAG50-zoreM",
    "poster": "https://i.ytimg.com/vi/SAG50-zoreM/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting loft ladder mounting brackets",
    "youtubeId": "-HK4OnTbhi4",
    "poster": "https://i.ytimg.com/vi/-HK4OnTbhi4/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Concealed slats for a flush finish",
    "youtubeId": "9y8ac04ylUA",
    "poster": "https://i.ytimg.com/vi/9y8ac04ylUA/hqdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Fitting a roof window",
    "youtubeId": "Y0iBkn1VU8Q",
    "poster": "https://i.ytimg.com/vi/Y0iBkn1VU8Q/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Where to find a roof window's data plate",
    "youtubeId": "8Z2N5BoYm84",
    "poster": "https://i.ytimg.com/vi/8Z2N5BoYm84/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Fitting a roof window U41",
    "youtubeId": "v5oLsLrVEM8",
    "poster": "https://i.ytimg.com/vi/v5oLsLrVEM8/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Fitting a roof window P50",
    "youtubeId": "CE22qOoiuCU",
    "poster": "https://i.ytimg.com/vi/CE22qOoiuCU/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Fitting an L-shaped window (part 2)",
    "youtubeId": "ISHgIW6qSas",
    "poster": "https://i.ytimg.com/vi/ISHgIW6qSas/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Fitting L-shaped windows (part 2)",
    "youtubeId": "ZpPrACudS_A",
    "poster": "https://i.ytimg.com/vi/ZpPrACudS_A/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Fitting a wooden terrace window",
    "youtubeId": "4h9caHsdAJE",
    "poster": "https://i.ytimg.com/vi/4h9caHsdAJE/maxresdefault.jpg"
  },
  {
    "label": "Flat roofs",
    "title": "Fitting a smoke ventilation flat roof window",
    "youtubeId": "r2LCsjLVwIM",
    "poster": "https://i.ytimg.com/vi/r2LCsjLVwIM/maxresdefault.jpg"
  },
  {
    "label": "Flat roofs",
    "title": "Fitting a flat roof window kerb",
    "youtubeId": "a42b78BJZBk",
    "poster": "https://i.ytimg.com/vi/a42b78BJZBk/maxresdefault.jpg"
  },
  {
    "label": "Flat roofs",
    "title": "Fitting a flat roof window",
    "youtubeId": "kWHe4WNX3dw",
    "poster": "https://i.ytimg.com/vi/kWHe4WNX3dw/maxresdefault.jpg"
  },
  {
    "label": "Blinds",
    "title": "Fitting a roller blind",
    "youtubeId": "wTdYd2JwW8k",
    "poster": "https://i.ytimg.com/vi/wTdYd2JwW8k/maxresdefault.jpg"
  },
  {
    "label": "Blinds",
    "title": "Fitting a roller blind electrical contact B",
    "youtubeId": "A8gTTa8m_cI",
    "poster": "https://i.ytimg.com/vi/A8gTTa8m_cI/maxresdefault.jpg"
  },
  {
    "label": "Blinds",
    "title": "Fitting a roller blind electrical contact A",
    "youtubeId": "adWcqt0D5DI",
    "poster": "https://i.ytimg.com/vi/adWcqt0D5DI/maxresdefault.jpg"
  },
  {
    "label": "Blinds",
    "title": "Fitting a roller blind electrical contact C",
    "youtubeId": "pkVMZAGyMz4",
    "poster": "https://i.ytimg.com/vi/pkVMZAGyMz4/maxresdefault.jpg"
  },
  {
    "label": "Blinds",
    "title": "Fitting a roller blind electrical contact D",
    "youtubeId": "uRlq5SJfufU",
    "poster": "https://i.ytimg.com/vi/uRlq5SJfufU/maxresdefault.jpg"
  },
  {
    "label": "Blinds",
    "title": "Fitting a roller blind, start to finish",
    "youtubeId": "K7XAP2BbL3A",
    "poster": "https://i.ytimg.com/vi/K7XAP2BbL3A/maxresdefault.jpg"
  },
  {
    "label": "Blinds",
    "title": "Fitting a semi-open roller blind",
    "youtubeId": "XzJm2PSqYvE",
    "poster": "https://i.ytimg.com/vi/XzJm2PSqYvE/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Fitting a side hung escape roof window",
    "youtubeId": "Glj_m1wVBh4",
    "poster": "https://i.ytimg.com/vi/Glj_m1wVBh4/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Fitting internal window linings",
    "youtubeId": "zLDeJ9D4HW0",
    "poster": "https://i.ytimg.com/vi/zLDeJ9D4HW0/maxresdefault.jpg"
  },
  {
    "label": "Flashings",
    "title": "Fitting a flashing",
    "youtubeId": "n3Ues-kwqVA",
    "poster": "https://i.ytimg.com/vi/n3Ues-kwqVA/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting a 60 fire-resistant attic ladder",
    "youtubeId": "3lsOcyySFeg",
    "poster": "https://i.ytimg.com/vi/3lsOcyySFeg/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting a metal attic ladder",
    "youtubeId": "RO6RW2ShTf4",
    "poster": "https://i.ytimg.com/vi/RO6RW2ShTf4/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting an insulated metal loft ladder",
    "youtubeId": "aaYu-aRUqnE",
    "poster": "https://i.ytimg.com/vi/aaYu-aRUqnE/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting a scissor loft ladder",
    "youtubeId": "92ZfG2v6ywA",
    "poster": "https://i.ytimg.com/vi/92ZfG2v6ywA/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting the electric loft ladder",
    "youtubeId": "M7Z--76e_b4",
    "poster": "https://i.ytimg.com/vi/M7Z--76e_b4/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting an insulated scissor loft ladder",
    "youtubeId": "8mZqTRY6PPU",
    "poster": "https://i.ytimg.com/vi/8mZqTRY6PPU/maxresdefault.jpg"
  },
  {
    "label": "Doors",
    "title": "Fitting an L-shaped door",
    "youtubeId": "EsuvKG_R12E",
    "poster": "https://i.ytimg.com/vi/EsuvKG_R12E/maxresdefault.jpg"
  },
  {
    "label": "Doors",
    "title": "Fitting a fire-resistant L-shaped combination door 60",
    "youtubeId": "iB4cL6k7fcI",
    "poster": "https://i.ytimg.com/vi/iB4cL6k7fcI/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Assembling a loft ladder upper hatch",
    "youtubeId": "enqLIvVNmoA",
    "poster": "https://i.ytimg.com/vi/enqLIvVNmoA/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting an unloading mechanism",
    "youtubeId": "MxPH-TQLGE0",
    "poster": "https://i.ytimg.com/vi/MxPH-TQLGE0/maxresdefault.jpg"
  },
  {
    "label": "Light tunnels",
    "title": "Where to find a light tunnel's data plate",
    "youtubeId": "qZMOUH7HBy8",
    "poster": "https://i.ytimg.com/vi/qZMOUH7HBy8/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Where to find a loft ladder's data plate",
    "youtubeId": "iudYF3YwjtI",
    "poster": "https://i.ytimg.com/vi/iudYF3YwjtI/maxresdefault.jpg"
  },
  {
    "label": "Real projects",
    "title": "The founder on thirty-five years of the business",
    "youtubeId": "cDOb5lTuuew",
    "poster": "https://i.ytimg.com/vi/cDOb5lTuuew/maxresdefault.jpg"
  },
  {
    "label": "Real projects",
    "title": "35 Years Together",
    "youtubeId": "DiU-3tUJIRQ",
    "poster": "https://i.ytimg.com/vi/DiU-3tUJIRQ/maxresdefault.jpg"
  },
  {
    "label": "Loft ladders",
    "title": "Fitting a ladder unloading mechanism",
    "youtubeId": "FCTt9n_JVgQ",
    "poster": "https://i.ytimg.com/vi/FCTt9n_JVgQ/hqdefault.jpg"
  },
  {
    "label": "Flat roofs",
    "title": "A skylight balcony on a TV home makeover",
    "youtubeId": "62CRw9cvKhk",
    "poster": "https://i.ytimg.com/vi/62CRw9cvKhk/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "A roof window that opens into a balcony",
    "youtubeId": "pcN9ZLlzjAE",
    "poster": "https://i.ytimg.com/vi/pcN9ZLlzjAE/maxresdefault.jpg"
  },
  {
    "label": "Real projects",
    "title": "Thirty-five years, and the range today",
    "youtubeId": "GKV-8abw8V0",
    "poster": "https://i.ytimg.com/vi/GKV-8abw8V0/hqdefault.jpg"
  },
  {
    "label": "Real projects",
    "title": "Case study - New penthouse in historic Vienna",
    "youtubeId": "ILO0OKGTnGw",
    "poster": "https://i.ytimg.com/vi/ILO0OKGTnGw/maxresdefault.jpg"
  },
  {
    "label": "Real projects",
    "title": "Groevenbeek Noord - Affordable housing and no energy costs",
    "youtubeId": "emO_VK3fKB8",
    "poster": "https://i.ytimg.com/vi/emO_VK3fKB8/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "Roof Windows – Energy Efficiency You Feel Every Day",
    "youtubeId": "5VMI_dskH2Q",
    "poster": "https://i.ytimg.com/vi/5VMI_dskH2Q/maxresdefault.jpg"
  },
  {
    "label": "Roof windows",
    "title": "The balcony window, close up",
    "youtubeId": "cwlSTNfIpqA",
    "poster": "https://i.ytimg.com/vi/cwlSTNfIpqA/maxresdefault.jpg"
  },
  {
    "label": "Real projects",
    "title": "Behind the Scenes – The Quiet That Helps Create a Peaceful Attic",
    "youtubeId": "8HayoUBzWFA",
    "poster": "https://i.ytimg.com/vi/8HayoUBzWFA/maxresdefault.jpg"
  }
];
