// GENERATED by scripts/build-noken-films.cjs — do not edit by hand.
// Bathroom films surveyed from a supplier site (1,189 English pages; the site
// republishes each page under twelve locale prefixes, which the survey skips),
// filtered to ids that still play, and de-branded — no supplier name and no
// range name, so the cards describe the job rather than the catalogue.
// Three are served from our own origin, mirrored by
// scripts/download-noken-videos.cjs. Re-run the build to refresh.
import type { ProjectFilm } from "@/components/home/RealProjects";

export const NOKEN_FILMS: ProjectFilm[] = [
  {
    "label": "Sustainability",
    "title": "Water as a shared resource",
    "src": "/home/real-projects/water-forest.mp4",
    "poster": "/home/real-projects/posters/water-forest.jpg"
  },
  {
    "label": "Sustainability",
    "title": "Comparing the energy two showers use",
    "src": "/home/real-projects/shower-energy-comparison.mp4",
    "poster": "/home/real-projects/posters/shower-energy-comparison.jpg"
  },
  {
    "label": "Bathroom design",
    "title": "An award-winning sculpted tap and basin",
    "src": "/home/real-projects/sculpted-tap-award.mp4",
    "poster": "/home/real-projects/posters/sculpted-tap-award.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the cartridge in a traditional floor-mounted bath tap",
    "youtubeId": "z2wgqSi0nKE",
    "poster": "https://i.ytimg.com/vi/z2wgqSi0nKE/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the cartridge in a contemporary floor-mounted bath tap",
    "youtubeId": "StXo8bC7HlA",
    "poster": "https://i.ytimg.com/vi/StXo8bC7HlA/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the cartridge in a minimalist floor-mounted bath tap",
    "youtubeId": "CyNz-Cs-M10",
    "poster": "https://i.ytimg.com/vi/CyNz-Cs-M10/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "How the diverter cartridge works on a floor-mounted bath mixer",
    "youtubeId": "R9qQqfRVpj0",
    "poster": "https://i.ytimg.com/vi/R9qQqfRVpj0/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the cartridge in a square-profile basin tap",
    "youtubeId": "AAzV2t_XftI",
    "poster": "https://i.ytimg.com/vi/AAzV2t_XftI/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the aerator on a square-profile basin tap",
    "youtubeId": "_tBwlMeHAks",
    "poster": "https://i.ytimg.com/vi/_tBwlMeHAks/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the cartridge in a single-lever basin tap",
    "youtubeId": "N-cwKhKHiqA",
    "poster": "https://i.ytimg.com/vi/N-cwKhKHiqA/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the cartridge in a curved basin tap",
    "youtubeId": "l-uWO5awHto",
    "poster": "https://i.ytimg.com/vi/l-uWO5awHto/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the cartridge in a compact basin tap",
    "youtubeId": "mOntNv72YJc",
    "poster": "https://i.ytimg.com/vi/mOntNv72YJc/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the cartridge in a lever mixer",
    "youtubeId": "HnhmCeqgtYo",
    "poster": "https://i.ytimg.com/vi/HnhmCeqgtYo/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the headworks in monobloc pillar taps",
    "youtubeId": "BcTazYK34AM",
    "poster": "https://i.ytimg.com/vi/BcTazYK34AM/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Changing a standard mixer tap cartridge",
    "youtubeId": "mUr_OYRlFJk",
    "poster": "https://i.ytimg.com/vi/mUr_OYRlFJk/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Changing the cartridge in a monobloc mixer tap",
    "youtubeId": "wkBZcx9EHC8",
    "poster": "https://i.ytimg.com/vi/wkBZcx9EHC8/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing a thermostatic tap cartridge",
    "youtubeId": "of_uMNrgrJg",
    "poster": "https://i.ytimg.com/vi/of_uMNrgrJg/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Calibrating a thermostatic cartridge",
    "youtubeId": "pS7F8rmY25s",
    "poster": "https://i.ytimg.com/vi/pS7F8rmY25s/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the cartridge in a cast-mineral tap",
    "youtubeId": "16WXIwJALeM",
    "poster": "https://i.ytimg.com/vi/16WXIwJALeM/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the cartridge in a kitchen pillar tap",
    "youtubeId": "H1VbiqeUMFo",
    "poster": "https://i.ytimg.com/vi/H1VbiqeUMFo/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Changing the cartridge in a slimline kitchen tap",
    "youtubeId": "5rvriQVx3lc",
    "poster": "https://i.ytimg.com/vi/5rvriQVx3lc/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing the cartridge in a pull-out kitchen tap",
    "youtubeId": "9Q8wjMQVvDg",
    "poster": "https://i.ytimg.com/vi/9Q8wjMQVvDg/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Replacing a concealed tap aerator",
    "youtubeId": "sxPBt-wEys8",
    "poster": "https://i.ytimg.com/vi/sxPBt-wEys8/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Changing a concealed basin-tap aerator",
    "youtubeId": "kkis89TthDQ",
    "poster": "https://i.ytimg.com/vi/kkis89TthDQ/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Removing a standard aerator",
    "youtubeId": "eutnaX9CS4I",
    "poster": "https://i.ytimg.com/vi/eutnaX9CS4I/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Removing a curved-range aerator",
    "youtubeId": "8NPWcgzQ1nE",
    "poster": "https://i.ytimg.com/vi/8NPWcgzQ1nE/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Removing a coin-slot aerator",
    "youtubeId": "XoT3cRJUn9s",
    "poster": "https://i.ytimg.com/vi/XoT3cRJUn9s/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Swapping a water breaker for an aerator",
    "youtubeId": "klHe4COjWq8",
    "poster": "https://i.ytimg.com/vi/klHe4COjWq8/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Stripping and rebuilding a sensor basin tap",
    "youtubeId": "sl6PYf6c12Y",
    "poster": "https://i.ytimg.com/vi/sl6PYf6c12Y/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Installing a mains-powered sensor basin mixer",
    "youtubeId": "jB4IMje7xFU",
    "poster": "https://i.ytimg.com/vi/jB4IMje7xFU/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Installing a battery-powered sensor basin mixer",
    "youtubeId": "-SihNfGlbDE",
    "poster": "https://i.ytimg.com/vi/-SihNfGlbDE/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Installing and commissioning a five-in-one kitchen tap",
    "youtubeId": "6DUt6yybyto",
    "poster": "https://i.ytimg.com/vi/6DUt6yybyto/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Changing the water filter in a filtered kitchen tap",
    "youtubeId": "0IpEMieP0Oc",
    "poster": "https://i.ytimg.com/vi/0IpEMieP0Oc/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Changing the CO₂ cylinder in a sparkling-water kitchen tap",
    "youtubeId": "dV89OQcoxmc",
    "poster": "https://i.ytimg.com/vi/dV89OQcoxmc/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Running the cleaning cycle on a filtered kitchen tap",
    "youtubeId": "PxktJmrJhqI",
    "poster": "https://i.ytimg.com/vi/PxktJmrJhqI/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Extra-flat rain shower heads with a safety valve",
    "youtubeId": "6X8EyFkk-_Q",
    "poster": "https://i.ytimg.com/vi/6X8EyFkk-_Q/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "A ceiling-recessed shower head",
    "youtubeId": "s74cA1FpD-g",
    "poster": "https://i.ytimg.com/vi/s74cA1FpD-g/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Pairing the remote control for a shower head",
    "youtubeId": "J08STIpsOoo",
    "poster": "https://i.ytimg.com/vi/J08STIpsOoo/maxresdefault.jpg"
  },
  {
    "label": "Taps & showers",
    "title": "Using a sanitary shower set correctly",
    "youtubeId": "kWXt-6DzPQE",
    "poster": "https://i.ytimg.com/vi/kWXt-6DzPQE/maxresdefault.jpg"
  },
  {
    "label": "Shower valves",
    "title": "Installing a concealed thermostatic valve box",
    "youtubeId": "AQnLlcdst8w",
    "poster": "https://i.ytimg.com/vi/AQnLlcdst8w/maxresdefault.jpg"
  },
  {
    "label": "Shower valves",
    "title": "Installing a single-outlet concealed valve box",
    "youtubeId": "uh9aI6sWP3A",
    "poster": "https://i.ytimg.com/vi/uh9aI6sWP3A/maxresdefault.jpg"
  },
  {
    "label": "Shower valves",
    "title": "Installing a multi-outlet concealed valve box",
    "youtubeId": "wEwwAM12LYg",
    "poster": "https://i.ytimg.com/vi/wEwwAM12LYg/maxresdefault.jpg"
  },
  {
    "label": "Shower valves",
    "title": "A slimline concealed thermostatic valve",
    "youtubeId": "YHxaISohNu0",
    "poster": "https://i.ytimg.com/vi/YHxaISohNu0/maxresdefault.jpg"
  },
  {
    "label": "Shower valves",
    "title": "A recessed slimline thermostatic valve box",
    "youtubeId": "eslPkyRBiY0",
    "poster": "https://i.ytimg.com/vi/eslPkyRBiY0/maxresdefault.jpg"
  },
  {
    "label": "Shower valves",
    "title": "A concealed thermostatic shower valve",
    "youtubeId": "ao9gyioi0fE",
    "poster": "https://i.ytimg.com/vi/ao9gyioi0fE/maxresdefault.jpg"
  },
  {
    "label": "Shower valves",
    "title": "Fitting a thermostatic valve with adjustable flow",
    "youtubeId": "Hk-uAgYJxeo",
    "poster": "https://i.ytimg.com/vi/Hk-uAgYJxeo/maxresdefault.jpg"
  },
  {
    "label": "Shower valves",
    "title": "Stripping and rebuilding a thermostatic shower column",
    "youtubeId": "4dB7sXyeOnw",
    "poster": "https://i.ytimg.com/vi/4dB7sXyeOnw/maxresdefault.jpg"
  },
  {
    "label": "Shower valves",
    "title": "Fitting a pressure-balance extension kit",
    "youtubeId": "Mcpzt75_ZG0",
    "poster": "https://i.ytimg.com/vi/Mcpzt75_ZG0/maxresdefault.jpg"
  },
  {
    "label": "Shower valves",
    "title": "Replacing the cartridges in a concealed shower valve",
    "youtubeId": "KXOuUYJW3SQ",
    "poster": "https://i.ytimg.com/vi/KXOuUYJW3SQ/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Installing a wall-hung pan",
    "youtubeId": "e-8lpKAdZ3w",
    "poster": "https://i.ytimg.com/vi/e-8lpKAdZ3w/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Installing a wall-hung toilet on a concealed frame",
    "youtubeId": "QQH4gJEq_zA",
    "poster": "https://i.ytimg.com/vi/QQH4gJEq_zA/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Installing a square-profile wall-hung toilet",
    "youtubeId": "EwfCrMWLCls",
    "poster": "https://i.ytimg.com/vi/EwfCrMWLCls/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "A contemporary wall-hung pan",
    "youtubeId": "pH-SV8OjJ60",
    "poster": "https://i.ytimg.com/vi/pH-SV8OjJ60/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Installing a wall-hung toilet on plasterboard and solid walls",
    "youtubeId": "hDa1Oue6ZtI",
    "poster": "https://i.ytimg.com/vi/hDa1Oue6ZtI/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Correcting the rock on a wall-hung toilet",
    "youtubeId": "4yricKxMceY",
    "poster": "https://i.ytimg.com/vi/4yricKxMceY/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Installing a concealed cistern frame on a solid wall",
    "youtubeId": "RMtIISygkA0",
    "poster": "https://i.ytimg.com/vi/RMtIISygkA0/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Building a concealed cistern into a solid wall",
    "youtubeId": "NvAY7YgrydM",
    "poster": "https://i.ytimg.com/vi/NvAY7YgrydM/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Installing a one-piece floor-standing toilet",
    "youtubeId": "JS74SpQd4Ms",
    "poster": "https://i.ytimg.com/vi/JS74SpQd4Ms/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Installing a one-piece toilet, step by step",
    "youtubeId": "8wdljsT7OhE",
    "poster": "https://i.ytimg.com/vi/8wdljsT7OhE/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Installing a toilet with a rear-inlet cistern",
    "youtubeId": "1VQWbZ4KdhQ",
    "poster": "https://i.ytimg.com/vi/1VQWbZ4KdhQ/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Fitting the mechanism in an accessible one-piece toilet",
    "youtubeId": "CLFxNbuRKrU",
    "poster": "https://i.ytimg.com/vi/CLFxNbuRKrU/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Adjusting the push-button rods on a one-piece toilet",
    "youtubeId": "lkDxF1IU2yQ",
    "poster": "https://i.ytimg.com/vi/lkDxF1IU2yQ/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Increasing the flush volume on a one-piece toilet",
    "youtubeId": "p3n_S-w_QVY",
    "poster": "https://i.ytimg.com/vi/p3n_S-w_QVY/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Fitting a dual-flush push button",
    "youtubeId": "-cVS2ZgM88E",
    "poster": "https://i.ytimg.com/vi/-cVS2ZgM88E/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Replacing the fill valve in a one-piece toilet",
    "youtubeId": "qY1tMe-nr8A",
    "poster": "https://i.ytimg.com/vi/qY1tMe-nr8A/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Replacing the flush valve in a one-piece toilet",
    "youtubeId": "khersBhfbZE",
    "poster": "https://i.ytimg.com/vi/khersBhfbZE/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Replacing a toilet fill-valve connector",
    "youtubeId": "M1a1_zQneWY",
    "poster": "https://i.ytimg.com/vi/M1a1_zQneWY/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Stripping and adjusting a contract cistern flush mechanism",
    "youtubeId": "2oggmbkDxCY",
    "poster": "https://i.ytimg.com/vi/2oggmbkDxCY/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Replacing the valves in a reduced-height concealed cistern",
    "youtubeId": "jTmgCGGnhzA",
    "poster": "https://i.ytimg.com/vi/jTmgCGGnhzA/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Replacing the flush and fill valves in a cistern frame",
    "youtubeId": "P5GlQIJIN8w",
    "poster": "https://i.ytimg.com/vi/P5GlQIJIN8w/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Setting the flush on a concealed cistern",
    "youtubeId": "8_8fllH4GG8",
    "poster": "https://i.ytimg.com/vi/8_8fllH4GG8/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Fitting a concealed cistern flush plate",
    "youtubeId": "v_oMvVdooJI",
    "poster": "https://i.ytimg.com/vi/v_oMvVdooJI/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Fitting the flush plate on a reduced-height frame",
    "youtubeId": "ow2TNX2JQG0",
    "poster": "https://i.ytimg.com/vi/ow2TNX2JQG0/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Fitting an odour-extraction adaptor kit",
    "youtubeId": "-DeOmNzQipI",
    "poster": "https://i.ytimg.com/vi/-DeOmNzQipI/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "Preventing toilet splashing",
    "youtubeId": "5OKNAr000-g",
    "poster": "https://i.ytimg.com/vi/5OKNAr000-g/maxresdefault.jpg"
  },
  {
    "label": "Toilets & cisterns",
    "title": "A rimless pan that stays clean",
    "vimeoId": "232316973",
    "poster": "https://i.vimeocdn.com/video/653344235-70fdb43183360ce1d5a000ec83769a8f4a1c218b97d2b2d4bfe929d0e9c17553-d_640?region=us"
  },
  {
    "label": "Toilet seats",
    "title": "Fitting a seat to a wall-hung pan",
    "youtubeId": "VNTKBb-4Q2w",
    "poster": "https://i.ytimg.com/vi/VNTKBb-4Q2w/maxresdefault.jpg"
  },
  {
    "label": "Toilet seats",
    "title": "Fitting a slimline toilet seat",
    "youtubeId": "Z5KHrUG9Hb0",
    "poster": "https://i.ytimg.com/vi/Z5KHrUG9Hb0/maxresdefault.jpg"
  },
  {
    "label": "Toilet seats",
    "title": "Fitting a wrapover toilet seat",
    "youtubeId": "RKeZgHjxBcU",
    "poster": "https://i.ytimg.com/vi/RKeZgHjxBcU/maxresdefault.jpg"
  },
  {
    "label": "Toilet seats",
    "title": "Fitting a soft-close toilet seat",
    "youtubeId": "fswmLSGt6B8",
    "poster": "https://i.ytimg.com/vi/fswmLSGt6B8/maxresdefault.jpg"
  },
  {
    "label": "Toilet seats",
    "title": "Fitting a soft-close seat and cover",
    "youtubeId": "hMY2WVuWlXc",
    "poster": "https://i.ytimg.com/vi/hMY2WVuWlXc/maxresdefault.jpg"
  },
  {
    "label": "Toilet seats",
    "title": "Replacing soft-close cartridges in a compact toilet seat",
    "youtubeId": "JUS0rzD6274",
    "poster": "https://i.ytimg.com/vi/JUS0rzD6274/maxresdefault.jpg"
  },
  {
    "label": "Toilet seats",
    "title": "Replacing soft-close cartridges in a wrapover seat",
    "youtubeId": "6Qj7m7tMAUE",
    "poster": "https://i.ytimg.com/vi/6Qj7m7tMAUE/maxresdefault.jpg"
  },
  {
    "label": "Toilet seats",
    "title": "A lift-off seat and cover",
    "vimeoId": "210220556",
    "poster": "https://i.vimeocdn.com/video/626161298-3f26b0b16ee56d0761eea14b512b2f24370612824e0aef5ed44fbc6d96a073d4-d_640?region=us"
  },
  {
    "label": "Toilet seats",
    "title": "Soft-close comfort on a toilet lid",
    "vimeoId": "572931213",
    "poster": "https://i.vimeocdn.com/video/1184795602-02fb8d8418a2f73930da32023141d633390b7791873a7030c05dd89e1021e10f-d_200x150?region=us"
  },
  {
    "label": "Toilet seats",
    "title": "The advantages of soft close",
    "vimeoId": "277614707",
    "poster": "https://i.vimeocdn.com/video/710430510-b2955a6497088461c5aeae79e8ecc852d11974581c708e2b5c70f3556d2d5b8b-d_640?region=us"
  },
  {
    "label": "Smart bathrooms",
    "title": "How a smart toilet works",
    "youtubeId": "iYUc5OiaVRU",
    "poster": "https://i.ytimg.com/vi/iYUc5OiaVRU/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "How a compact smart toilet works",
    "youtubeId": "XC-ux1QuB-Q",
    "poster": "https://i.ytimg.com/vi/XC-ux1QuB-Q/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "How a project-spec smart toilet works",
    "youtubeId": "1hJHtk1Y-DM",
    "poster": "https://i.ytimg.com/vi/1hJHtk1Y-DM/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "A smart toilet with advanced comfort functions",
    "youtubeId": "PaYS1x4xBUo",
    "poster": "https://i.ytimg.com/vi/PaYS1x4xBUo/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Installing a compact smart toilet",
    "youtubeId": "_ahc457dpuY",
    "poster": "https://i.ytimg.com/vi/_ahc457dpuY/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Installing a project-spec smart toilet",
    "youtubeId": "MgmH34CKYV8",
    "poster": "https://i.ytimg.com/vi/MgmH34CKYV8/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Removing and refitting a smart toilet seat",
    "youtubeId": "i6Da4tDNTh4",
    "poster": "https://i.ytimg.com/vi/i6Da4tDNTh4/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Removing and refitting a compact smart toilet seat",
    "youtubeId": "HZZIFhOW8SM",
    "poster": "https://i.ytimg.com/vi/HZZIFhOW8SM/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Replacing the deodorising cartridge in a smart toilet",
    "youtubeId": "B0z1zbODIcc",
    "poster": "https://i.ytimg.com/vi/B0z1zbODIcc/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Replacing the extractor in an odour-extraction frame",
    "youtubeId": "C2JFz5TeOWg",
    "poster": "https://i.ytimg.com/vi/C2JFz5TeOWg/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Replacing the filter in an odour-extraction frame",
    "youtubeId": "WAqU3EtG6M4",
    "poster": "https://i.ytimg.com/vi/WAqU3EtG6M4/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "A multifunction filtered kitchen tap",
    "youtubeId": "QptQJQfTYTY",
    "poster": "https://i.ytimg.com/vi/QptQJQfTYTY/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Installing a sensor flush valve",
    "youtubeId": "2ph2bPBc6_s",
    "poster": "https://i.ytimg.com/vi/2ph2bPBc6_s/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Adjusting the infrared sensor on a urinal",
    "youtubeId": "Qf2vvl6amCM",
    "poster": "https://i.ytimg.com/vi/Qf2vvl6amCM/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Avoiding problems with infrared sensors",
    "youtubeId": "ABsv68um7Ic",
    "poster": "https://i.ytimg.com/vi/ABsv68um7Ic/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Using a sensor remote control",
    "youtubeId": "yshzErwP-xY",
    "poster": "https://i.ytimg.com/vi/yshzErwP-xY/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "Using the remote control on a touchless soap dispenser",
    "youtubeId": "9WSVvs-y6wk",
    "poster": "https://i.ytimg.com/vi/9WSVvs-y6wk/maxresdefault.jpg"
  },
  {
    "label": "Smart bathrooms",
    "title": "An intelligent toilet",
    "vimeoId": "204496445",
    "poster": "https://i.vimeocdn.com/video/619023915-1b70ac3e8e109ca16004d2e0bbfc722e0a2fae893e427bce9b3b63ec87b0665c-d_640?region=us"
  },
  {
    "label": "Smart bathrooms",
    "title": "A filtered kitchen tap, close up",
    "vimeoId": "1079700266",
    "poster": "https://i.vimeocdn.com/video/2010144013-5148b293fb1680acf893144e0419ef92dac017177fad23e188e6048883f805b2-d_200x150?region=us"
  },
  {
    "label": "Smart bathrooms",
    "title": "A bathroom range in augmented reality",
    "vimeoId": "133141481",
    "poster": "https://i.vimeocdn.com/video/526099803-4dc44a622cae25ad01dda2d7106b6dc235010c95746a50014be6f41339bf8aa3-d_295x166?region=us"
  },
  {
    "label": "Baths",
    "title": "Installing a freestanding bath and floor-mounted tap",
    "youtubeId": "4ZsC5pxFvOM",
    "poster": "https://i.ytimg.com/vi/4ZsC5pxFvOM/maxresdefault.jpg"
  },
  {
    "label": "Baths",
    "title": "Fitting a bath panel",
    "youtubeId": "0L61jx69Vyk",
    "poster": "https://i.ytimg.com/vi/0L61jx69Vyk/maxresdefault.jpg"
  },
  {
    "label": "Baths",
    "title": "Fitting a modular bath panel",
    "youtubeId": "bM2HJ_s2ud4",
    "poster": "https://i.ytimg.com/vi/bM2HJ_s2ud4/maxresdefault.jpg"
  },
  {
    "label": "Baths",
    "title": "Removing and refitting a round bath panel",
    "youtubeId": "jVRpvOtInd4",
    "poster": "https://i.ytimg.com/vi/jVRpvOtInd4/maxresdefault.jpg"
  },
  {
    "label": "Baths",
    "title": "Replacing a bath waste kit",
    "youtubeId": "6qIsnIrEEX0",
    "poster": "https://i.ytimg.com/vi/6qIsnIrEEX0/maxresdefault.jpg"
  },
  {
    "label": "Baths",
    "title": "Wellness sensations in the bath",
    "vimeoId": "258949450",
    "poster": "https://i.vimeocdn.com/video/687265426-6151c617c0dae70b059fc58d983e323b386be6c9109df49bb7fe001f1e9ab228-d_640?region=us"
  },
  {
    "label": "Baths",
    "title": "A whirlpool bath full of sensation",
    "vimeoId": "335338224",
    "poster": "https://i.vimeocdn.com/video/781884287-04102b6067d098f66618033490885994463d24404a61d5b3fcf64e40de82c5a9-d_295x166?region=us"
  },
  {
    "label": "Shower trays",
    "title": "Cutting a shower tray to size",
    "youtubeId": "RyI2A84boqg",
    "poster": "https://i.ytimg.com/vi/RyI2A84boqg/maxresdefault.jpg"
  },
  {
    "label": "Shower trays",
    "title": "Repairing a shower tray",
    "youtubeId": "37KrN7uyx_s",
    "poster": "https://i.ytimg.com/vi/37KrN7uyx_s/maxresdefault.jpg"
  },
  {
    "label": "Shower trays",
    "title": "Installing a cast-stone shower tray",
    "youtubeId": "uSTviCsYDy0",
    "poster": "https://i.ytimg.com/vi/uSTviCsYDy0/maxresdefault.jpg"
  },
  {
    "label": "Shower trays",
    "title": "Installing a mineral-stone shower tray",
    "youtubeId": "Gu3POukGLwQ",
    "poster": "https://i.ytimg.com/vi/Gu3POukGLwQ/maxresdefault.jpg"
  },
  {
    "label": "Bathroom furniture",
    "title": "Closing the gap between a vanity unit and the wall",
    "youtubeId": "CFpXtBc7GNs",
    "poster": "https://i.ytimg.com/vi/CFpXtBc7GNs/maxresdefault.jpg"
  },
  {
    "label": "Bathroom furniture",
    "title": "Adjusting the height of a vanity drawer",
    "youtubeId": "0b_ITnQRjqc",
    "poster": "https://i.ytimg.com/vi/0b_ITnQRjqc/maxresdefault.jpg"
  },
  {
    "label": "Bathroom furniture",
    "title": "Removing and refitting a vanity drawer",
    "youtubeId": "DiB0UzUHgqs",
    "poster": "https://i.ytimg.com/vi/DiB0UzUHgqs/maxresdefault.jpg"
  },
  {
    "label": "Bathroom furniture",
    "title": "Setting the runners on a vanity drawer",
    "youtubeId": "dq1ZHjU3HGM",
    "poster": "https://i.ytimg.com/vi/dq1ZHjU3HGM/maxresdefault.jpg"
  },
  {
    "label": "Bathroom furniture",
    "title": "Installing a faceted vanity unit",
    "youtubeId": "rFEpadYcvS8",
    "poster": "https://i.ytimg.com/vi/rFEpadYcvS8/maxresdefault.jpg"
  },
  {
    "label": "Heated towel rails",
    "title": "Bleeding a heated towel rail",
    "youtubeId": "J52JbSwZq-w",
    "poster": "https://i.ytimg.com/vi/J52JbSwZq-w/maxresdefault.jpg"
  },
  {
    "label": "Heated towel rails",
    "title": "Purging an electric heated towel rail",
    "youtubeId": "4D5EUoqE4jc",
    "poster": "https://i.ytimg.com/vi/4D5EUoqE4jc/maxresdefault.jpg"
  },
  {
    "label": "Heated towel rails",
    "title": "How the smart thermostat works",
    "youtubeId": "4qyKAZJTLuE",
    "poster": "https://i.ytimg.com/vi/4qyKAZJTLuE/maxresdefault.jpg"
  },
  {
    "label": "Heated towel rails",
    "title": "How the eco thermostat works",
    "youtubeId": "GOjcLDoLOXw",
    "poster": "https://i.ytimg.com/vi/GOjcLDoLOXw/maxresdefault.jpg"
  },
  {
    "label": "Heated towel rails",
    "title": "How the programmable thermostat works",
    "youtubeId": "5c957BLl2og",
    "poster": "https://i.ytimg.com/vi/5c957BLl2og/maxresdefault.jpg"
  },
  {
    "label": "Heated towel rails",
    "title": "Using the programmable thermostat remote control",
    "youtubeId": "p-f7XGrPhlU",
    "poster": "https://i.ytimg.com/vi/p-f7XGrPhlU/maxresdefault.jpg"
  },
  {
    "label": "Heated towel rails",
    "title": "Locking and unlocking the thermostat keypad",
    "youtubeId": "0IKGDbofAzs",
    "poster": "https://i.ytimg.com/vi/0IKGDbofAzs/maxresdefault.jpg"
  },
  {
    "label": "Bathroom care",
    "title": "Disinfecting a thermostatic valve with hot water",
    "youtubeId": "Nu5DLDYw2XE",
    "poster": "https://i.ytimg.com/vi/Nu5DLDYw2XE/maxresdefault.jpg"
  },
  {
    "label": "Bathroom care",
    "title": "Removing micro-scratches from solid-surface finishes",
    "youtubeId": "7PmwrHddjP4",
    "poster": "https://i.ytimg.com/vi/7PmwrHddjP4/maxresdefault.jpg"
  },
  {
    "label": "Bathroom care",
    "title": "Polishing cast-mineral baths and basins",
    "youtubeId": "QJJlJL39M_Q",
    "poster": "https://i.ytimg.com/vi/QJJlJL39M_Q/maxresdefault.jpg"
  },
  {
    "label": "Bathroom care",
    "title": "Repairing a scratch on a transparent resin bath or basin",
    "youtubeId": "W8XCd_3amSE",
    "poster": "https://i.ytimg.com/vi/W8XCd_3amSE/maxresdefault.jpg"
  },
  {
    "label": "Bathroom care",
    "title": "Caring for a cast-mineral surface",
    "youtubeId": "MQ6NfjBQvxo",
    "poster": "https://i.ytimg.com/vi/MQ6NfjBQvxo/maxresdefault.jpg"
  },
  {
    "label": "Bathroom care",
    "title": "A care system for bathroom surfaces",
    "youtubeId": "Z16yAhrFRi4",
    "poster": "https://i.ytimg.com/vi/Z16yAhrFRi4/maxresdefault.jpg"
  },
  {
    "label": "Bathroom care",
    "title": "Extending the life of a shower head",
    "youtubeId": "_xLSHDIn_d4",
    "poster": "https://i.ytimg.com/vi/_xLSHDIn_d4/maxresdefault.jpg"
  },
  {
    "label": "Bathroom care",
    "title": "Finding the spare parts list for a product",
    "youtubeId": "-VWeZ_-6Ldk",
    "poster": "https://i.ytimg.com/vi/-VWeZ_-6Ldk/maxresdefault.jpg"
  },
  {
    "label": "Bathroom design",
    "title": "Water as a state of inspiration",
    "vimeoId": "386662398",
    "poster": "https://i.vimeocdn.com/video/850336847-7af27902ebf6b42ff01c64edf8d5d125fc468528efbbe38aa71c1a1bbd58cd85-d_295x166?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "We create the difference",
    "vimeoId": "253212171",
    "poster": "https://i.vimeocdn.com/video/683614621-2c4d2e7b1b747bab1ab67ee97eee96078e948e1b4fef9270c8bc772039f6ae2b-d_640?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "We all need me-time",
    "vimeoId": "460085862",
    "poster": "https://i.vimeocdn.com/video/961154278-113d6020e149af0c0a4b9673d2416c04fc4fbe42a566fc5464cddcb313ba77de-d_295x166?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "Ceramic, up close",
    "vimeoId": "185444513",
    "poster": "https://i.vimeocdn.com/video/595191131-af29a316c2d97e854cc8cc39a62e8d78a647712109f8e578c33f3d8cf2f451a4-d_640?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "Choosing a metal finish in the finish studio",
    "vimeoId": "517104225",
    "poster": "https://i.vimeocdn.com/video/1074957434-e1b5a162c506dbb4d590fe1932f9d516ca948a4c4efb04c185000cfb839067e1-d_295x166?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "A matt black finish",
    "vimeoId": "580704558",
    "poster": "https://i.vimeocdn.com/video/1201594142-16d7b8923087e7de35dc409c681f094f54faac5ad63b4cc00273b6f308a537a0-d_295x166?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "Created by water — a sculptural collection",
    "vimeoId": "182108031",
    "poster": "https://i.vimeocdn.com/video/590893282-59097bed54726743a26933289a415b7015204713f9afdd1f5cddb7b39afb7c6f-d_640?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "Inside the sculptural collection",
    "vimeoId": "175496153",
    "poster": "https://i.vimeocdn.com/video/590889782-c3adf22f94aedc6d2aac00fb7a6453e21b416dc250f9875da52a7e18d767e2c3-d_640?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "Discovering the sculptural collection",
    "vimeoId": "180139972",
    "poster": "https://i.vimeocdn.com/video/590889420-c84a49ab42015a70f7636085019f7cd0380c2e34c01124220ac9840149595ce5-d_640?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "A designer collection by an architecture studio",
    "vimeoId": "179013445",
    "poster": "https://i.vimeocdn.com/video/590891835-dbc0dab1f81a6677ff19f022117d3ee99c4f60d320e6bcf65a21d81c9a3c5930-d_640?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "An architect on fifteen years of a bathroom collection",
    "vimeoId": "913664252",
    "poster": "https://i.vimeocdn.com/video/1799606632-9073b3f8244ed8b7d36d8ac0be8f3d68d540c54c4a1bb674ca230eb33ecc562e-d_295x166?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "Upcoming tradition — a designer tap collection",
    "vimeoId": "291645746",
    "poster": "https://i.vimeocdn.com/video/727839468-ad079214a6078d07208e2a8dab3c93745b77ddb1f9f276062da7b8eebc7003e8-d_640?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "A premium collection by a Spanish architect",
    "vimeoId": "145537538",
    "poster": "https://i.vimeocdn.com/video/543704442-049f537e0bdd996fa993341be27f339ef62a436819b5362ca9a48a1bfdeca155-d_640?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "Small designer bathrooms where every centimetre counts",
    "vimeoId": "159379541",
    "poster": "https://i.vimeocdn.com/video/561112335-9a1827e2bf80b60113de3e08f615235a6fab30b17addb256dbabd77537069f3c-d_640?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "A designer on exclusivity in design",
    "vimeoId": "130191619",
    "poster": "https://i.vimeocdn.com/video/521953099-b88becd0a89c5f32aab244057e9cf8f4361babbabf2f1fa8ae317924e0bf2cf5-d_295x166?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "An architect on architectural tradition",
    "vimeoId": "130191620",
    "poster": "https://i.vimeocdn.com/video/521952966-1f92ef9956f453c0d1b1fe9d5da70f3db2d8ff787fa627791178edb4340c3edd-d_295x166?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "The power of a unique design",
    "vimeoId": "137117242",
    "poster": "https://i.vimeocdn.com/video/539494776-cd98be276bba29c7aacca838767722af19534a0f6abc60eba3a8136a5d69adee-d_295x166?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "Innovation in Japan",
    "vimeoId": "77968822",
    "poster": "https://i.vimeocdn.com/video/453265192-77344dcfefbe26bac7aa764151021973dc74d6204cae8297924acb02a7aaf9d3-d_295x166?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "A new licensing agreement for packaging",
    "vimeoId": "289839297",
    "poster": "https://i.vimeocdn.com/video/725578206-7b61d6fdcd0bc2569b8a88e6c4a9bd5a53fb5858ac9e073bcaf328c1c84dfbbe-d_640?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "Feel with a simple touch — a thermostatic shower column",
    "vimeoId": "356868879",
    "poster": "https://i.vimeocdn.com/video/810068075-a79e61547e9a3be5a513dc3dd0ee47168f21e7a2e4f6e57a9abf8e0a52fe3a73-d_295x166?region=us"
  },
  {
    "label": "Bathroom design",
    "title": "A seventies-inspired bathroom, with an interior designer",
    "youtubeId": "QLUK7xfnV-8",
    "poster": "https://i.ytimg.com/vi/QLUK7xfnV-8/maxresdefault.jpg"
  },
  {
    "label": "Showrooms",
    "title": "Inside the 2017 showroom",
    "vimeoId": "206024935",
    "poster": "https://i.vimeocdn.com/video/620939646-0d7b681c8687637a9354b4fb3f2835d2a46b59828c6a696fd40e3c611e9e517a-d_640?region=us"
  },
  {
    "label": "Showrooms",
    "title": "Inside the 2018 showroom",
    "vimeoId": "254324446",
    "poster": "https://i.vimeocdn.com/video/681443822-c76eeded153ba9714d59dbeb55b2a535a93a06ce2677dbbd9774c34097a0f1da-d_640?region=us"
  },
  {
    "label": "Real projects",
    "title": "Professional assistance on site",
    "vimeoId": "296371223",
    "poster": "https://i.vimeocdn.com/video/734040038-cadd70dfee1abe461e8e720090ef8ed9d7eb46966b37f705d4bfd595c74cdd5e-d_640?region=us"
  },
  {
    "label": "Real projects",
    "title": "Working with the group's partners",
    "vimeoId": "221393100",
    "poster": "https://i.vimeocdn.com/video/639646569-d790f37689e0a3cd601eef213b272d46b2a183ce3058eb963a5ff546dcfb1190-d_640?region=us"
  },
  {
    "label": "Real projects",
    "title": "An invitation to the international exhibition",
    "vimeoId": "386432643",
    "poster": "https://i.vimeocdn.com/video/848970042-12d106ab7cbb5d9be2a7fbbb4ff1c61180413292131d15bf39142f757a07b64b-d_200x150?region=us"
  },
  {
    "label": "Real projects",
    "title": "Highlights from the 2018 international exhibition",
    "vimeoId": "249635784",
    "poster": "https://i.vimeocdn.com/video/675505127-a10c7bb2f2f5f3885b5a1144d734695f669b89c6de010cac46f14aee7d752d07-d_640?region=us"
  },
  {
    "label": "Real projects",
    "title": "Highlights from the 26th international exhibition",
    "vimeoId": "313752536",
    "poster": "https://i.vimeocdn.com/video/755490819-fca59fefad576088ada9433ba42e20486af163ef9ffb686689f8c4883b1b0a55-d_640?region=us"
  },
  {
    "label": "Real projects",
    "title": "Bathrooms at a hotel interiors show",
    "vimeoId": "371192038",
    "poster": "https://i.vimeocdn.com/video/828625078-38a960c4c7d4dd618bd713da68a708002b78e1122443621dfa8db58b82c5880e-d_200x150?region=us"
  },
  {
    "label": "Real projects",
    "title": "At a Paris design fair",
    "vimeoId": "356641766",
    "poster": "https://i.vimeocdn.com/video/809775400-7ad4e2fb8072bb123374fb898a9e46dcec49808ecaf93d94267bd10669103df9-d_200x150?region=us"
  },
  {
    "label": "Real projects",
    "title": "On the stand at a Bologna trade fair",
    "vimeoId": "547470839",
    "poster": ""
  },
  {
    "label": "Real projects",
    "title": "An architect on innovation",
    "vimeoId": "129890868",
    "poster": "https://i.vimeocdn.com/video/521544093-bd40355961e7d64a525dece0f9a12fc209d2a28906f030f8c12e34b237b693fb-d_295x166?region=us"
  },
  {
    "label": "Sustainability",
    "title": "How much water and energy a shower uses",
    "vimeoId": "846152297",
    "poster": "https://i.vimeocdn.com/video/1698984568-5fde7893b89464bad7411cae9be0af8fda83362477f582ae88ee80a911ae3f8e-d_295x166?region=us"
  },
  {
    "label": "Sustainability",
    "title": "A shower system built to save energy",
    "vimeoId": "812405611",
    "poster": "https://i.vimeocdn.com/video/1658339829-0b7922eaab80f268b80d8d9178ec9e43a27d54f15697f27de676bcc1f6766d3a-d_295x166?region=us"
  },
  {
    "label": "Sustainability",
    "title": "Cold-water opening taps",
    "vimeoId": "128120121",
    "poster": "https://i.vimeocdn.com/video/519133101-34a2b21914cb2767958dd8bbdcc4a9561d1af764f13535a2891af98627f6b0b7-d_295x166?region=us"
  },
  {
    "label": "Sustainability",
    "title": "A commitment to water",
    "vimeoId": "310969527",
    "poster": "https://i.vimeocdn.com/video/752081336-a0dd97fe1489226103a665b831f958127769d49d0079f84953894f241e60c0e5-d_295x166?region=us"
  },
  {
    "label": "Sustainability",
    "title": "Washing hands, saving water",
    "vimeoId": "400917465",
    "poster": ""
  },
  {
    "label": "Sustainability",
    "title": "Cold-start taps that save energy",
    "youtubeId": "pA0M0FM52ZM",
    "poster": "https://i.ytimg.com/vi/pA0M0FM52ZM/maxresdefault.jpg"
  },
  {
    "label": "Sustainability",
    "title": "Thirty per cent of production energy from solar",
    "youtubeId": "KwFk21p0NZo",
    "poster": "https://i.ytimg.com/vi/KwFk21p0NZo/maxresdefault.jpg"
  }
];
