// GENERATED by scripts/build-pooky-films.cjs — do not edit by hand.
// Lighting films surveyed from a supplier site, de-branded, and filtered to
// ids that still play and are actually theirs. The site self-hosts nothing, so
// every card here is an embed. Re-run the build to refresh.
import type { ProjectFilm } from "@/components/home/RealProjects";

export const POOKY_FILMS: ProjectFilm[] = [
  {
    "label": "Lighting design",
    "title": "How to light a home, with an interior design studio",
    "youtubeId": "Wl6D6BV8eEI",
    "poster": "https://i.ytimg.com/vi/Wl6D6BV8eEI/maxresdefault.jpg"
  },
  {
    "label": "Lighting design",
    "title": "A classic lamp, redrawn",
    "vimeoId": "1172187672",
    "poster": "https://i.vimeocdn.com/video/2131938131-c6948da933aa944b24a2800ba2670520639bd3f8dcd6d58b9e26f5cae406de78-d_200x150?region=us"
  },
  {
    "label": "Lamp care",
    "title": "Removing a lampshade reducer ring",
    "youtubeId": "OfZcJBWT8K4",
    "poster": "https://i.ytimg.com/vi/OfZcJBWT8K4/maxresdefault.jpg"
  },
  {
    "label": "Lamp care",
    "title": "Straightening a lamp ball joint",
    "youtubeId": "NcOU7KnQxzk",
    "poster": "https://i.ytimg.com/vi/NcOU7KnQxzk/maxresdefault.jpg"
  },
  {
    "label": "Lamp care",
    "title": "Reattaching a bulb holder",
    "youtubeId": "D7NtfI5gqWs",
    "poster": "https://i.ytimg.com/vi/D7NtfI5gqWs/hqdefault.jpg"
  },
  {
    "label": "Lamp care",
    "title": "Changing a fuse",
    "youtubeId": "7ZgNcwBbNww",
    "poster": "https://i.ytimg.com/vi/7ZgNcwBbNww/maxresdefault.jpg"
  }
];
