// Copied unchanged from testing-app/web/src/engine/tileCore.glsl.js (room visualiser engine).
// Keep in sync with that file; do not edit here.
/**
 * The shared tiling core.
 *
 * Both renderers need identical bond patterns, joints and relighting; they
 * differ only in how a screen pixel becomes a position in metres on the
 * surface -- a homography for a flat photo, a ray/plane intersection for a
 * panorama. Everything that does not depend on that lives here, so the two
 * paths can never drift apart.
 *
 * Declares the product/joint/relight uniforms as well, so a shader only has to
 * add its own geometry uniforms on top.
 *
 * `shadeSurface` returns a vec4: rgb plus its own coverage. Not every material
 * fills the surface it is applied to -- a rug covers a rectangle of the floor
 * and the grout visualizer covers only the joints -- so the alpha channel is
 * how a material says "leave the photograph showing here".
 */
export const TILE_CORE = /* glsl */ `
// --- product ---------------------------------------------------------------
uniform sampler2D uTile;       // tile texture atlas (faces stacked vertically)
uniform float uFaces;          // how many random faces the atlas holds
uniform vec2  uTileSize;       // module / repeat / piece size in metres (w, h)
uniform vec3  uTint;
uniform int   uMaterial;       // which rendering model, see MODEL_* below
uniform vec3  uColor;          // flat colour for the solid model (paint)
uniform vec2  uPlaneSize;      // the surface's own size in metres, for centring

// --- bond pattern ----------------------------------------------------------
uniform int   uLayout;
uniform float uRotation;       // radians, spins the pattern on the plane
uniform vec2  uOffset;         // metres, slides the pattern on the plane
uniform float uRandomFace;
uniform float uRandomRotate;

// --- joints ----------------------------------------------------------------
uniform float uGrout;          // joint width in metres
uniform vec3  uGroutColor;
uniform float uBevel;          // edge shading strength

// --- relighting ------------------------------------------------------------
uniform float uRefLevel;       // reference luminance of the original surface
uniform float uShade;          // 0 = flat, 1 = full original lighting
uniform float uDetail;         // how much fine photo texture shows through
uniform float uGloss;          // 0 matt .. 1 polished
uniform float uOpacity;

const int LAYOUT_GRID           = 0;
const int LAYOUT_BRICK          = 1;
const int LAYOUT_BRICK_THIRD    = 2;
const int LAYOUT_VERTICAL       = 3;
const int LAYOUT_VERTICAL_BRICK = 4;
const int LAYOUT_HERRINGBONE    = 5;
const int LAYOUT_BASKETWEAVE    = 6;
const int LAYOUT_DIAGONAL       = 7;
const int LAYOUT_DIAGONAL_BRICK = 8;

// Rendering models. Must match MODELS in layouts.js.
const int MODEL_MODULE = 0;    // discrete units with joints: tile, plank, panel
const int MODEL_SHEET  = 1;    // one continuous repeat: wallpaper, carpet, epoxy
const int MODEL_SOLID  = 2;    // flat colour with a sheen: paint
const int MODEL_PIECE  = 3;    // a single bounded rectangle: rug
const int MODEL_JOINT  = 4;    // recolour the photographed joints only: grout

float hash21(vec2 p) {
  p = fract(p * vec2(123.34, 345.45));
  p += dot(p, p + 34.345);
  return fract(p.x * p.y);
}

vec2 rot2(vec2 v, float a) {
  float s = sin(a), c = cos(a);
  return vec2(c * v.x - s * v.y, s * v.x + c * v.y);
}

/** Result of resolving a metre position against the bond pattern. */
struct Cell {
  vec2  local;   // position inside the cell, metres, origin at cell corner
  vec2  size;    // this cell's size in metres (swapped when laid sideways)
  vec2  id;      // stable per-tile id, for random face / rotation
  float turned;  // 1.0 when the tile is laid at 90 degrees
};

/** What a material puts on the plane, before the room's light is applied. */
struct Lay {
  vec3  base;      // material colour at this point
  float alpha;     // how much of the photograph this material covers
  float specMask;  // where the sheen is allowed to land
};

/**
 * Axis-aligned running bond. The off argument shifts each course sideways;
 * 0 gives a stack bond, 0.5 a classic brick, 1/3 a third-brick.
 */
Cell bondCell(vec2 p, vec2 cell, float off) {
  float row = floor(p.y / cell.y);
  float lx = p.x - row * off * cell.x;
  float col = floor(lx / cell.x);
  Cell c;
  c.local = vec2(lx - col * cell.x, p.y - row * cell.y);
  c.size = cell;
  c.id = vec2(col, row);
  c.turned = 0.0;
  return c;
}

/**
 * Herringbone. Tiles of L x W meet end-to-side in a zig-zag. The tiling is
 * generated by the lattice a = (W, W), b = (-L, L) with one horizontal tile at
 * [0,L)x[0,W) and one vertical tile at [L, L+W) x [W-L, W). The fundamental
 * domain is L-shaped rather than a parallelogram, so the resolver probes back
 * up to ceil(L / 2W) steps along a and one along b -- bounds measured over the
 * whole plane for ratios from 1:1 to 6:1.
 */
Cell herringboneCell(vec2 p, vec2 cell) {
  float L = max(cell.x, cell.y);
  float W = min(cell.x, cell.y);
  float det = 2.0 * W * L;
  vec2 base = floor(vec2((L * p.x + L * p.y) / det, (-W * p.x + W * p.y) / det));
  float span = ceil(L / (2.0 * W));

  Cell c;
  c.size = vec2(L, W);
  c.local = vec2(0.0);
  c.id = vec2(0.0);
  c.turned = 0.0;

  for (int j = 0; j <= 1; j++) {
    for (int i = 0; i < 8; i++) {
      if (float(i) > span) break;
      vec2 k = base + vec2(-float(i), float(j));
      vec2 q = p - k.x * vec2(W, W) - k.y * vec2(-L, L);
      if (q.x >= 0.0 && q.x < L && q.y >= 0.0 && q.y < W) {
        c.local = q;
        c.size = vec2(L, W);
        c.id = k;
        return c;
      }
      if (q.x >= L && q.x < L + W && q.y >= W - L && q.y < W) {
        c.local = vec2(q.x - L, q.y - (W - L));
        c.size = vec2(W, L);
        c.id = k + vec2(0.5, 0.5);
        c.turned = 1.0;
        return c;
      }
    }
  }
  return c;
}

/**
 * Basketweave. Groups of k = round(L/W) tiles form squares of side L; those
 * squares alternate between horizontal and vertical across the plane.
 */
Cell basketweaveCell(vec2 p, vec2 cell) {
  float L = max(cell.x, cell.y);
  float W = min(cell.x, cell.y);
  float k = max(1.0, floor(L / W + 0.5));
  float band = L / k;

  vec2 g = floor(p / L);
  vec2 q = p - g * L;
  bool horiz = mod(g.x + g.y, 2.0) < 0.5;

  Cell c;
  if (horiz) {
    float b = floor(q.y / band);
    c.local = vec2(q.x, q.y - b * band);
    c.size = vec2(L, band);
    c.id = g * 8.0 + vec2(0.0, b);
    c.turned = 0.0;
  } else {
    float b = floor(q.x / band);
    c.local = vec2(q.x - b * band, q.y);
    c.size = vec2(band, L);
    c.id = g * 8.0 + vec2(b, 4.0);
    c.turned = 1.0;
  }
  return c;
}

Cell resolveCell(vec2 p, vec2 cell) {
  if (uLayout == LAYOUT_BRICK)           return bondCell(p, cell, 0.5);
  if (uLayout == LAYOUT_BRICK_THIRD)     return bondCell(p, cell, 1.0 / 3.0);
  if (uLayout == LAYOUT_VERTICAL)        return bondCell(p, cell.yx, 0.0);
  if (uLayout == LAYOUT_VERTICAL_BRICK)  return bondCell(p, cell.yx, 0.5);
  if (uLayout == LAYOUT_HERRINGBONE)     return herringboneCell(p, cell);
  if (uLayout == LAYOUT_BASKETWEAVE)     return basketweaveCell(p, cell);
  if (uLayout == LAYOUT_DIAGONAL_BRICK)  return bondCell(p, cell, 0.5);
  return bondCell(p, cell, 0.0);
}

/**
 * How much of this pixel is tile face rather than joint, plus the cell it
 * landed in. Shared by the module model (which draws the face) and the joint
 * model (which draws only what is left over).
 */
float jointCoverage(vec2 p, vec2 rdx, vec2 rdy, float aa, out Cell cell,
                    out vec2 inTile, out vec2 face, out float resolves) {
  vec2 course = uTileSize + vec2(uGrout);
  cell = resolveCell(p, course);

  inTile = cell.local - vec2(uGrout * 0.5);
  face = max(cell.size - vec2(uGrout), vec2(1e-5));
  float edge = min(min(inTile.x, face.x - inTile.x),
                   min(inTile.y, face.y - inTile.y));

  // Once a pixel spans a whole tile there is no joint left to resolve, only
  // its average. Crossfading to the analytic coverage ratio is what keeps a
  // floor receding to the horizon from breaking into moire.
  float crisp = smoothstep(-aa, aa, edge);
  float coverAvg = (face.x * face.y) / max(cell.size.x * cell.size.y, 1e-9);
  resolves = clamp(min(cell.size.x, cell.size.y) / (4.0 * aa), 0.0, 1.0);
  return uGrout <= 0.0 ? 1.0 : mix(coverAvg, crisp, resolves);
}

/** Discrete units with joints -- tile, stone, plank, carpet tile, wall panel. */
Lay layModule(vec2 p, vec2 rdx, vec2 rdy, float aa) {
  Cell cell;
  vec2 inTile, face;
  float resolves;
  float tileMask = jointCoverage(p, rdx, rdy, aa, cell, inTile, face, resolves);

  vec2 uvT = clamp(inTile / face, 0.0, 1.0);
  if (cell.turned > 0.5) uvT = vec2(uvT.y, 1.0 - uvT.x);

  float r = hash21(cell.id + 3.17);
  if (uRandomRotate > 0.5) {
    float quarter = floor(hash21(cell.id + 9.31) * 4.0);
    for (int i = 0; i < 3; i++) {
      if (float(i) < quarter) uvT = vec2(uvT.y, 1.0 - uvT.x);
    }
  }

  float faceIdx = uRandomFace > 0.5 ? floor(r * uFaces) : 0.0;
  vec2 atlasUv = vec2(uvT.x, (uvT.y + faceIdx) / uFaces);

  vec2 duv = vec2(1.0) / face;
  vec2 gx = vec2(rdx.x * duv.x, rdx.y * duv.y / uFaces);
  vec2 gy = vec2(rdy.x * duv.x, rdy.y * duv.y / uFaces);
  vec3 tileCol = textureGrad(uTile, atlasUv, gx, gy).rgb * uTint;

  float edge = min(min(inTile.x, face.x - inTile.x),
                   min(inTile.y, face.y - inTile.y));
  float bevelBand = uGrout * 1.6 + aa;
  float bevel = 1.0 - uBevel * resolves * (1.0 - smoothstep(0.0, max(bevelBand, 1e-5), edge));
  tileCol *= mix(1.0, bevel, tileMask);

  vec3 base = mix(uGroutColor, tileCol, tileMask);
  base *= mix(0.88, 1.0, tileMask);

  vec3 avg = textureLod(uTile, vec2(0.5, 0.5), 9.0).rgb * uTint;
  base = mix(mix(avg, uGroutColor, 0.18), base, resolves);

  Lay l;
  l.base = base;
  l.alpha = 1.0;
  l.specMask = mix(0.35, 1.0, tileMask);
  return l;
}

/**
 * One continuous pattern repeating over the plane -- wallpaper, broadloom
 * carpet, poured epoxy. There is no joint to resolve, so uTileSize is the
 * pattern repeat rather than a unit size, and nothing here reads uGrout.
 */
Lay laySheet(vec2 p, vec2 rdx, vec2 rdy) {
  vec2 rep = max(uTileSize, vec2(1e-4));
  vec2 uvT = fract(p / rep);
  vec2 atlasUv = vec2(uvT.x, uvT.y / uFaces);

  // Gradients from the unwrapped coordinate: taking them from the wrapped one
  // would spike at every repeat boundary and draw a seam right across it.
  vec2 gx = vec2(rdx.x / rep.x, rdx.y / rep.y / uFaces);
  vec2 gy = vec2(rdy.x / rep.x, rdy.y / rep.y / uFaces);

  Lay l;
  l.base = textureGrad(uTile, atlasUv, gx, gy).rgb * uTint;
  l.alpha = 1.0;
  l.specMask = 1.0;
  return l;
}

/** A flat colour with no texture at all -- paint. */
Lay laySolid() {
  Lay l;
  l.base = uColor * uTint;
  l.alpha = 1.0;
  l.specMask = 1.0;
  return l;
}

/**
 * A single bounded rectangle laid on the plane -- a rug.
 *
 * Centred on the surface and moved by uOffset, so the whole rectangle sits
 * where it was put rather than tiling away to the horizon. Outside it the
 * alpha goes to zero and the photograph is simply left alone.
 */
Lay layPiece(vec2 world, float rot, vec2 rdx, vec2 rdy, float aa) {
  // Named halfSize, not half: "half" is a reserved word in GLSL ES, and using
  // it fails to compile the whole core -- which takes every surface shader
  // down with it, not just the rug.
  vec2 halfSize = max(uTileSize, vec2(1e-4)) * 0.5;
  vec2 q = rot2(world - uPlaneSize * 0.5, rot) - uOffset;

  vec2 d = abs(q) - halfSize;
  float outside = max(d.x, d.y);
  float edgeAA = max(aa, 1e-6);

  Lay l;
  l.alpha = 1.0 - smoothstep(-edgeAA, edgeAA, outside);
  l.specMask = 1.0;
  l.base = vec3(0.0);
  if (l.alpha <= 0.001) return l;

  vec2 uvT = clamp((q + halfSize) / (halfSize * 2.0), 0.0, 1.0);
  vec2 atlasUv = vec2(uvT.x, uvT.y / uFaces);
  vec2 duv = vec2(0.5) / halfSize;
  vec2 gx = vec2(rdx.x * duv.x, rdx.y * duv.y / uFaces);
  vec2 gy = vec2(rdy.x * duv.x, rdy.y * duv.y / uFaces);
  l.base = textureGrad(uTile, atlasUv, gx, gy).rgb * uTint;
  return l;
}

/**
 * Recolour the joints of the surface already in the photograph.
 *
 * The reference makes a separate "grout visualizer" of this: keep the tile the
 * customer already has and only change the grout. Line the pattern up with the
 * photographed floor using the same size and bond controls, and this draws the
 * new joint colour into the gaps -- alpha is zero over the tile faces, so they
 * stay exactly as photographed.
 */
Lay layJoint(vec2 p, vec2 rdx, vec2 rdy, float aa) {
  Cell cell;
  vec2 inTile, face;
  float resolves;
  float tileMask = jointCoverage(p, rdx, rdy, aa, cell, inTile, face, resolves);

  Lay l;
  l.base = uGroutColor;
  // Fade out as the joints stop being resolvable, rather than smearing a
  // coloured haze over the far half of the floor.
  l.alpha = (1.0 - tileMask) * resolves;
  l.specMask = 0.2;
  return l;
}

/**
 * Lay the product at a point on the surface and relight it.
 *
 * world      position on the plane, in metres
 * dWdx/dWdy  how far that position moves per screen pixel, for antialiasing
 * lum        .r blurred luminance of the plate, .g raw -- the room's own light
 *
 * Returns rgb plus the coverage this material claims, which is not always 1.
 */
vec4 shadeSurface(vec2 world, vec2 dWdx, vec2 dWdy, vec2 lum) {
  float stretch = max(length(dWdx), length(dWdy));
  float aa = max(stretch * 0.6, 1e-6);

  bool diag = (uLayout == LAYOUT_DIAGONAL || uLayout == LAYOUT_DIAGONAL_BRICK);
  float rot = uRotation + (diag ? 0.7853981634 : 0.0);
  vec2 p = rot2(world, rot) + uOffset;
  vec2 rdx = rot2(dWdx, rot);
  vec2 rdy = rot2(dWdy, rot);

  Lay l;
  if (uMaterial == MODEL_SHEET)      l = laySheet(p, rdx, rdy);
  else if (uMaterial == MODEL_SOLID) l = laySolid();
  else if (uMaterial == MODEL_PIECE) l = layPiece(world, rot, rdx, rdy, aa);
  else if (uMaterial == MODEL_JOINT) l = layJoint(p, rdx, rdy, aa);
  else                               l = layModule(p, rdx, rdy, aa);

  if (l.alpha <= 0.001) return vec4(0.0);

  float ref = max(uRefLevel, 0.004);
  float shade = pow(clamp(lum.r / ref, 0.04, 6.0), uShade);
  vec3 lit = l.base * shade;

  float hf = (lum.g - lum.r) / ref;
  lit *= 1.0 + hf * uDetail;

  float spec = max(lum.g - ref, 0.0) / ref;
  lit += uGloss * spec * spec * l.specMask;

  return vec4(max(lit, vec3(0.0)), l.alpha);
}
`;
